### ISSUE TITLE
the issue about multiple image import

### ISSUE THREAD

**Issue by fejich** [aboood40091/GTX-Extractor#4]
I am currently working on "**Mario Vs. Donkey Kong: Tipping Stars**" in the Chinese Localization

This game has a lot of gtx files containing multiple images，export the file is normal.
There are some gtx files even beyond the **TexConv2.exe** can only import 64 pictures of the restrictions, there are 153 pictures in the inside.

But,when I edit the dds file, use the -multi option to import the file
Everything looks normal, but I cover it back after the game. Picture position only blank

Can you help me to see what is going on?

**I uploaded files to Google Drive:**https://drive.google.com/open?id=0B6rm6RJxJJ4ORTUxbDkxVXFtN3M

Have time to hope that you can analyze what is the problem somewhere. Thank you

**Comment by aboood40091** [comment]
Hmm, sadly, I think I can't help you with this one. Sorry.

**Comment by fejich** [comment]
This morning I observed that the **TexConv2.exe** generated contains **multiple images gtx** file

I used **HxD.exe** observation to find the law, TexConv2.exe just a number of dds → gtx data one by one **paste in the same file** inside.

So I divided the **153** dds files into **three groups**

- 0-63
- 64-127
- 128-152

Generate three gtx files, and then manually copy the need to use data, this approach is successful!

Problem fixed :)


_PS: GTX-Extractor generated gtx file with TexConv2 generated file is a little bit different, it may be the reason that the game can not be properly identified_

**Comment by aboood40091** [comment]
Huh.

Nah, it can't be the problem. I think the problem is something else.
